[package]
name = "be_eloistree_hellocrate"
version = "0.1.2"
edition = "2021"
authors =["Eloi Stree"]
description="My first Hello Crate"
license="Beerware"

[dependencies]
rand = "0.8.4"



[profile.dev]
opt-level=0

[profile.release]
opt-level=3